const paragraphs = [
    "Writing clean code is not just a best practice, it's a mindset that makes your programs more readable and maintainable.",
    "Debugging is like being the detective in a criminal movie where you are also the murderer.",
    "In programming, you are bound to encounter bugs, but it’s how you handle them that defines your coding journey.",
    "A well-designed algorithm is like a well-oiled machine, smoothly handling every task with minimal friction.",
    "The true power of programming lies not just in the lines of code you write, but in the solutions you create.",
    "Code should be written for humans to read, and only secondarily for machines to execute.",
    "A great programmer is someone who can solve a problem, not just write code.",
    "Programming is like solving puzzles, where the pieces fit together through logic and creativity.",
    "The best programmers aren’t necessarily the ones who write the most code, but the ones who write the best code.",
    "Learning to program is like learning a new language; it takes time, practice, and patience.",
    "Don’t be afraid to fail in programming; each error is an opportunity to improve your skills.",
    "A good function is one that solves a problem, is reusable, and is easy to understand.",
    "Code refactoring is like cleaning up your room: it might take a little time, but it’s worth it in the end.",
    "The most important rule in programming is to keep it simple and elegant.",
    "Every bug you fix is a step forward in becoming a better developer.",
    "Writing efficient code is more than just optimizing performance; it's about making code that is scalable and maintainable.",
    "Programming requires persistence, attention to detail, and a willingness to learn from mistakes.",
    "The best code isn’t always the one that works, but the one that is easy to maintain and extend.",
    "Learning programming is like solving a series of puzzles, where every solution unlocks a new challenge.",
    "Great programmers know that their code is never truly finished; it’s always a work in progress.",
    "A programmer is someone who can turn coffee into code and make it work.",
    "To write good code, you must think like a computer but write like a human.",
    "Code that works is good, but code that’s clean, readable, and efficient is better.",
    "The key to being a good programmer is not knowing everything, but knowing how to find the answers.",
    "Programmers don't write code in a vacuum; they work in teams and communicate effectively to build great software.",
    "The hardest part of programming is not writing the code, but understanding the problem you’re trying to solve.",
    "A great algorithm is one that is elegant, efficient, and solves the problem in the most straightforward way.",
    "In programming, learning never stops. The best developers are always looking to improve their skills.",
    "You know you’re a programmer when you start dreaming in code.",
    "Code is like humor: when you have to explain it, it’s bad.",
    "In programming, the best way to learn is by doing, so get your hands dirty and start coding.",
    "Programming isn’t just about writing code; it’s about solving real-world problems with technology.",
    "Good programmers know how to debug, but great programmers know how to avoid bugs in the first place.",
    "The art of programming is not just about writing code, but about creating something meaningful and impactful.",
    "The true value of a programmer is not just in their ability to write code, but in their ability to solve problems effectively."
];

const translations = [
    "Escrever código limpo não é apenas uma boa prática, é uma mentalidade que torna seus programas mais legíveis e manuteníveis.",
    "Depuração é como ser o detetive em um filme de crime onde você também é o assassino.",
    "Na programação, você certamente encontrará bugs, mas é a forma como você os lida que define sua jornada de codificação.",
    "Um algoritmo bem projetado é como uma máquina bem lubrificada, lidando suavemente com cada tarefa com mínima fricção.",
    "O verdadeiro poder da programação não está apenas nas linhas de código que você escreve, mas nas soluções que você cria.",
    "O código deve ser escrito para ser lido por humanos e, em segundo lugar, para ser executado por máquinas.",
    "Um grande programador é aquele que pode resolver um problema, não apenas escrever código.",
    "Programar é como resolver quebra-cabeças, onde as peças se encaixam através da lógica e criatividade.",
    "Os melhores programadores não são necessariamente os que escrevem mais código, mas os que escrevem o melhor código.",
    "Aprender a programar é como aprender um novo idioma; leva tempo, prática e paciência.",
    "Não tenha medo de errar na programação; cada erro é uma oportunidade para melhorar suas habilidades.",
    "Uma boa função é aquela que resolve um problema, é reutilizável e fácil de entender.",
    "Refatoração de código é como limpar o seu quarto: pode levar um pouco de tempo, mas vale a pena no final.",
    "A regra mais importante na programação é mantê-la simples e elegante.",
    "Cada bug que você corrige é um passo para se tornar um desenvolvedor melhor.",
    "Escrever código eficiente é mais do que apenas otimizar o desempenho; trata-se de criar um código escalável e manutenível.",
    "Programação exige persistência, atenção aos detalhes e disposição para aprender com os erros.",
    "O melhor código não é sempre o que funciona, mas o que é fácil de manter e expandir.",
    "Aprender a programar é como resolver uma série de quebra-cabeças, onde cada solução desbloqueia um novo desafio.",
    "Grandes programadores sabem que seu código nunca está verdadeiramente terminado; está sempre em progresso.",
    "Um programador é alguém que pode transformar café em código e fazer funcionar.",
    "Para escrever um bom código, você deve pensar como um computador, mas escrever como um ser humano.",
    "Código que funciona é bom, mas código limpo, legível e eficiente é melhor.",
    "A chave para ser um bom programador não é saber tudo, mas saber como encontrar as respostas.",
    "Programadores não escrevem código no vácuo; eles trabalham em equipes e se comunicam efetivamente para construir um ótimo software.",
    "A parte mais difícil da programação não é escrever o código, mas entender o problema que você está tentando resolver.",
    "Um grande algoritmo é aquele que é elegante, eficiente e resolve o problema da maneira mais simples.",
    "Na programação, o aprendizado nunca para. Os melhores desenvolvedores estão sempre procurando melhorar suas habilidades.",
    "Você sabe que é um programador quando começa a sonhar com código.",
    "Código é como humor: quando você tem que explicar, está ruim.",
    "Na programação, a melhor forma de aprender é praticando, então suje suas mãos e comece a programar.",
    "Programar não é apenas escrever código; é resolver problemas do mundo real com tecnologia.",
    "Bons programadores sabem como depurar, mas grandes programadores sabem como evitar bugs desde o início.",
    "A arte de programar não é apenas escrever código, mas criar algo significativo e impactante.",
    "O verdadeiro valor de um programador não está apenas na sua capacidade de escrever código, mas na sua habilidade de resolver problemas de forma eficaz."
];
